lamda_sta   = 10;
lamda_end   = 40;
neuron_n    = 1000;
lamda_int   = (lamda_end - lamda_sta)/neuron_n;
lamda_part  = lamda_sta:lamda_int:(lamda_end - lamda_int);
lamda_tmp   = 1.0./(lamda_part');
% lamda_tmp   = flip(lamda_tmp);

choose_rand = 1;

if choose_rand==1
    lamda_tmp_2 = lamda_tmp(end:-1:1);
    lamda_tmp   = [lamda_tmp, lamda_tmp_2];
end

cns('new', ...
    'lamda', lamda_tmp, ...
    'tmax', 0.5, ...
    'ln_time', 10, ...
    'display_per_time', 10, ...
    'save_per_time', 10, ...
    'neuron_n', 20, ...
    'save_sig', 0, ...
    'sig_from_file', 0, ...
    'save_file_name', 'save_new_test_fre_inc_rand', ...
    'save_sig_file', 'data/test_save_inc_rand', ...
    'save_sig_name', 'oja', ...
    'g_max', 0.025, ...
    'A_neg', 1.05*0.001, ...
    'choose_rand', choose_rand, ...
    'initial_A', 0.3, ...
    'with_speed', 1 ...
    );
% 
%     'cont', 1, ...
%     'cont_file', 'save_new_test_fre_inc_2', ...