init_g_a    = 0.4;
lamda_sta   = 10;
lamda_end   = 40;
neuron_n    = 1000;
lamda_int   = (lamda_end - lamda_sta)/neuron_n;
lamda_part  = lamda_sta:lamda_int:(lamda_end - lamda_int);
lamda_tmp   = 1.0./([lamda_part, 10*ones(1, 200)]');

% lamda_tmp_2 = [flip(lamda_tmp(1:neuron_n));lamda_tmp(neuron_n+1:neuron_n+200)];
% lamda_tmp   = [lamda_tmp, lamda_tmp_2];
% lamda_tmp   = 1.0./[15];
time_all    = 1000;
% lamda_tmp   = 1.0./(15:10:20);

cns('ss00', ...
    'mode_pic', 0, ...
    'tmax', 20, ...
    'save_prefix', 'ss00_tmax_50_finc_2_', ...
    'display_mode', 1, ...
    'with_speed', 0, ...
    'neg_speed', 0.5, ...
    'fix_g_a', 0, ...
    'init_g_a', init_g_a, ...
    'sep_g_a', 0, ...
    'neg_speed_tao', 80.0/1000, ...
    'A_neg', 0.005*1.05, ...
    'A_pos', 0.005, ...
    'lamda', lamda_tmp, ...
    'sep_sig', 0, ...
    'an_lamda', 1.0/25, ...
    'cont', 0,...
    'save_data_path', 'ss00_tmax_50_wo_lim_data_15',...
    'without_limit', 0, ...
    'choose_rand', 1, ...
    'rand_seed', 1, ...
    'randn_seed', 1, ...
    'time_simu ',time_all);
%     'A_neg', 0.006, ...
%         'tao_ex', 10.0/1000, ...