cns('ss01', ...
    'input_bar_pic', 1,...
    'input_bar_2d', 0, ...
    'sig_n', 1600, ...
    'ex_n',16, ...
    'sig_to_ex_conn_rate', 0.35, ...
    'g_max', 0.04, ...
    'pixel_size', 2, ...
    'with_speed', 1 ...
    );
%     'input_bar_pic_simple', 0, ...
%     'A_neg', 0.0012 ...